### ISSUE TITLE
dump in server-side page-generating functions dumps the continuation

### ISSUE THREAD

**Issue by elordin** [links-lang/links#274] opened 2017-09-23 15:33 UTC
Minimal example:
```
fun myPage (path) {
  dump(5);
  page <h1>Hello World</h1>
}

fun main () {
  addRoute("/", myPage);
  servePages()
}

main()
```
When navigating to `/`, which should show **Hello World**, it displays the encoded continuation.
Source of that page is the continuation only, so no `<html>`, `<head>`, etc. either.

**Comment by dhil** [comment] 2019-01-30 12:33
I believe this is a duplicate of #154. The general problem is that client-side functions cannot be invoked during page generation. The function `dump` is a client side function. Closing as a duplicate of #154.

**Closed by dhil** 2019-01-30 12:33 UTC
Labels: bug
