### ISSUE TITLE
Decouple show_compiled_ir_after_backend_transformations from typecheck_ir

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#561] opened 2019-04-11 13:25 UTC
Currently `show_compiled_ir_after_backend_transformations` setting only takes effect when `typecheck_ir` is enabled. I don't this needs to be the case. I'd like to be able to see the generated IR even if it isn't getting typechecked.

**Comment by frank-emrich** [comment] 2019-04-11 13:32
I agree. It could be changed such that it unconditionally happens at the end of the backend pipeline. I placed it before the IR type-checker to catch any side-effects that the IR type-checking may (unintentionally) have when using some helper functions (e.g., from `Instantiate`, `Types`).

I didn't bother to do this before because we should then also rethink the naming.
We have `show_pre_frontend_ast` and  `show_post_frontend_ast`, so we may rename `show_compiled_ir` and `show_compiled_ir_after_backend_transformations` to mirror this:
```
show_pre_backend_ir
show_post_backend_ir
```

But I'm not sure how people feel about renaming `show_compiled_ir`, which they are used to.

**Comment by jstolarek** [comment] 2019-04-11 13:40
> I didn't bother to do this before because we should then also rethink the naming.

Not just the naming. It seems that we want to be able to dump the AST in various stages of the compilation pipeline. So far this has been implemented in an ad-hoc manner. We should think whether this can be structured in some reasonable way.

**Comment by frank-emrich** [comment] 2019-04-11 13:44
> It seems that we want to be able to dump the AST in various stages of the compilation pipeline. 

Yes, we may think about something like an option for dumping the IR after each transformation pass. On the other hand, as soon as I'm interested in something like that I'm usually deep in some debugging and will add the necessary printing at the right place.

**Comment by jamescheney** [comment] 2019-04-12 09:00
We should serialize all of the intermediate ASTs in the form of a web page with "forward" and "back" buttons so you can see how the AST evolves after each stage.  Only semi-kidding.

**Comment by dhil** [comment] 2019-08-13 18:36
A much more ergonomic solution is to give proper names to each phase of the compiler (a simple scheme would be to just number them). Get rid of all the tedious `show_blah_after_more_blah_this_setting_is_rather_long` settings. Instead support multi options or  interpret the string of `@show_compiled_ir` as a small DSL (a la OCaml's warning CLI option), i.e. `@show_compiled_ir 1-3,5,8` would show the IR after phases 1, 2, 3, 5, and 8.

> We should serialize all of the intermediate ASTs in the form of a web page with "forward" and "back" buttons so you can see how the AST evolves after each stage. Only semi-kidding.

Regardless, we really ought to support serialisation of each intermediate AST form. Implementing a debugger/visualiser or website could be a internship project.

**Comment by dhil** [comment] 2019-08-13 19:34
> Currently show_compiled_ir_after_backend_transformations setting only takes effect when typecheck_ir is enabled. I don't this needs to be the case. I'd like to be able to see the generated IR even if it isn't getting typechecked.

So I looked into the issue you describe here. As far as I can tell it makes little sense to enable `show_compiled_ir_after_backend_transformations` if  `typecheck_ir` isn't set to true, as the transformations (poor choice of word by the way) are only run to simplify the type structure prior to invoking the type checker.

If you really want them decoupled, then I suggest introducing another phase call `simplfy_ir_types` which determines whether the simplification phase is run. I am unsure whether the IR type checker may depend on the type structure being simplified prior to invocation, if that is the case then I think that is a IR type checker bug.

**Comment by jstolarek** [comment] 2019-08-14 06:45
> A much more ergonomic solution is to give proper names to each phase of the compiler

I agree that some flag names get too long, but I'm not convinced that using numbers instead would be better. I fear that I would either have to memorize which number corresponds to which phase or constantly check the documentation (which we don't have...). The flag names are long, yes, but having a config file and (un)commenting lines as necessary is easy and fast.

> As far as I can tell it makes little sense to enable `show_compiled_ir_after_backend_transformations` if `typecheck_ir` isn't set to true, as the transformations (poor choice of word by the way) are only run to simplify the type structure prior to invoking the type checker.

Indeed, that dependence between simplifying pass and IR typechecker looks strange. However I believe what I need makes perfect sense. At the moment there is no way to display the compiled IR unless IR typechecking is enabled. This should not be the case, these should really be two independent things. As such, this ticket is not resolved so I'm reopening.

Also, it would be nice to leave more time for discussion rather than just a short 1,5h window in the late evening. Some of us prefer to work in the evenings, others in the morning.

**Comment by jamescheney** [comment] 2019-08-14 08:11
@dhil I would also appreciate if you could leave a day or so for review of PRs / discussion of issue closing.  Also please keep in mind that you are 8 hours ahead of us so daytime for you is late evening/early morning for us.

**Comment by dhil** [comment] 2019-08-14 15:36
> At the moment there is no way to display the compiled IR unless IR typechecking is enabled. This should not be the case, these should really be two independent things. As such, this ticket is not resolved so I'm reopening.

You can dump the IR from sugartoir by setting `show_compiled_ir` to `true`.

> @dhil I would also appreciate if you could leave a day or so for review of PRs / discussion of issue closing. Also please keep in mind that you are 8 hours ahead of us so daytime for you is late evening/early morning for us.

I was demoing Links over here. In hindsight I should probably had separated the PR into two or had the participants running of my forked Links (sub-optimal). The latter bug prevented me from showcasing interactive IR type checking. However, time was of the essence, so I made a swift move and fixed it.

**Comment by jamescheney** [comment] 2019-08-14 16:04
> I was demoing Links over here.... The latter bug prevented me from showcasing interactive IR type checking.

Great!  I hadn't realized that we had reached a point where showing new people the IR typechecker (or indeed, enabling it by default) was something we were doing.  I had the impression that there were still enough unresolved things about this that it was intended for our use only for now.  I'd be curious to hear more about how it went, and if there are other things that can be fixed to make it more demo-able.

**Comment by dhil** [comment] 2019-08-14 17:14
I have reverted #715 and reopened it as #718 with comments by @jstolarek addressed. The PR solves the issue described in the title of this ticket. I think the other "issue" 

> I'd like to be able to see the generated IR even if it isn't getting typechecked.

Is a non-issue as you can already dump the IR using `show_compiled_ir`. With #718 you can even dump it after type simplifications by setting `show_compiled_ir_after_backend_transformations`.

**Comment by jstolarek** [comment] 2019-08-15 09:47
Not sure why I didn't notice `show_compiled_ir` despite searching through `basicsettings.ml` at least twice :-/

**Closed** 2019-08-15 19:52 UTC
Labels: confusion, enhancement
