### ISSUE TITLE
IR typing: Miscellanea

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#446] opened 2018-12-30 16:56 UTC
This issue collects some simple examples that illustrate ill-typed IR being generated:

The (anonymous identity function or a constant function:
```
fun (x) {x};
fun (x) {1};
```
both result in IR with unbound type variables.

```
for (x <- []) []
```
yields an "inorrect type annotation on a (unused) variable" error.  

There is also
```
fun () {query {[]}};
```
has  an "incompatible effects" error.

The anonymous composition function:
```
fun (f,g) {fun (x){f (g(x))}};
```
produces several unbound type variables, plus a "Providing closure to untracked function" error.

```
fun (x) {<a>{x}</a>}
```
produces a type mismatch between `[XmlItem]` and `Xml`, which may indicate a limitation in the IR typing rather than wrong behavior, since `Xml` is supposed to be a type alias for `[XmlItem]`.

**Comment by frank-emrich** [comment] 2018-12-30 17:47
The unbound type variable problems for the first two functions sound like instances of the problem originally reported here:
https://github.com/links-lang/links/issues/377

In short, when generating a polymorphic IR function, the type variable used for the type abstraction (e.g., /\ X. ....) is different from the type variable that is used in the type annotation (\forall Y. ....) for that function. This seems to be by design and shouldn't be a problem in general. However, the frontend mixes those two variables up occasionally. This means that the variable from the type annotation (Y) is suddenly used inside of terms (e.g., by type applications), where X should be used instead. This results in the IR typechecker (rightfully) reporting unbound type variables.

This problem occurs even in the simplest examples. However, I'm hestitant to touch the corresponding frontend code since I don't feel like I'm understanding all the brittle invariants sufficiently.

**Comment by jamescheney** [comment] 2018-12-30 18:09
In the simplest cases (identity/constant functions) I'm seeing compiled IR like this:
```
([`Fun (((2113, ((_) -> Int, "_fun__g142", `Local)),
         ([], [(2112, (_, "", `Local))],
          ([`Let (((2111, (_, "x", `Local)), ([], `Return (`Variable (2112)))))
             ],
           `Return (`Constant (`Int (1))))),
         None, `Unknown))
   ],
 `Return (`TAbs (([a; a::Row(Any,Any)], `Variable (2113)))))
```

One problem is that the type printing is printing out user-friendly type syntax and hiding the actual type variable IDs.  However, it also looks like the expression generated starts with a function binding, and the end result is a type abstraction expression that binds the type variables over the function name. 

 This just looks wrong to me!  The Fun binding doesn't introduce any type variables, and the function body using type variables is not in the lexical scope of the binding introduced by TAbs.  I think the correct end result should look something like:

```
([`Fun (((2113, ((b) -> Int, "_fun__g142", `Local)),
         ([b], [(2112, (b, "", `Local))],
          ([`Let (((2111, (b, "x", `Local)), ([], `Return (`Variable (2112)))))
             ],
           `Return (`Constant (`Int (1))))),
         None, `Unknown))
   ],
 `Return (`TAbs (([a; a::Row(Any,Any)], `Closure(2113,[a],emptyEnv)))))
```

or even just

```
([`Fun (((2113, ((b) -> Int, "_fun__g142", `Local)),
         ([b], [(2112, (b, "", `Local))],
          ([`Let (((2111, (b, "x", `Local)), ([], `Return (`Variable (2112)))))
             ],
           `Return (`Constant (`Int (1))))),
         None, `Unknown))
   ],
 `Return (`Variable(2113))
```

**Comment by frank-emrich** [comment] 2018-12-30 18:50
> One problem is that the type printing is printing out user-friendly type syntax and hiding the actual type variable IDs.

There is a setting `show_raw_type_vars`, which should give you the actual names of the involved type variables instead of letters. Furthermore, the setting `print_types_pretty` will give you the raw AST of types when printing them, instead of a pretty-printed version.

**Comment by jamescheney** [comment] 2018-12-30 19:37
Thanks.  I tried that and it's almost too much information :) but better than too little.  It does confirm that the type variable is out of (lexical) scope.  BY enabling various debugging messages, I think I've determined that this is the case before closure conversion starts, i.e. desugaring is generating code as shown above.  (It appears show_compiled_ir shows the IR before closure conversion.)

**Comment by jamescheney** [comment] 2018-12-30 20:19
I've also noticed that the identity / constant functions are translated correctly if they are given as named declarations rather than anonymous functions.  Named declarations seem to be treated as declarations (Fun) as opposed to anonymous function expressions (FunLit).  This makes me wonder if there is some overlap with #437, where there also seemed to be a difference between how named and anonymous functions are handled.

OK, so in `desugarFuns.ml`, `FunLit` constructs are desugared to `Fun` declarations with no free type variables.  This makes a certain amount of sense because we don't want to generalize over free type variables of arbitrary function literals in the middle of code, so it might be correct as far as it goes, but function literals can also occur in places where generalization is sound (and is performed by type inference), for example as a toplevel expression or on the RHS of a variable binding.  However, it looks like what is happening is that later, a TAbs is inserted to account for ForAll type of the overall expression, but at that point it's too late to make things match up again.  So perhaps this should be happening earlier, such as by inserting an appropriate TAbstr at whatever part of desugaring/typechecking we can determine that a function literal can have a generalizable type.

**Comment by jstolarek** [comment] 2019-03-20 11:00
I did my own investigation on the subject of different treatment of anonymous vs. named functions and arrived at the same conclusions as @jamescheney. Anonymous functions are represented as `FunLit` phrases, named as `Fun` bindings. Type variables of `Fun`s are filled in during typechecking (in `typeSugar.ml`), which does not happen for `FunLit`s. Then `desugarFuns.ml` converts `FunLit`s to `Fun`s but does not fill in tyvars, leaving them as `[]`.

I think it would be fairly easy to add a `tyvars` field to `FunLit` and fill it in during typechecking, but from what @jamescheney says that would only be valid in some contexts and not in others:

> we don't want to generalize over free type variables of arbitrary function literals in the middle of code

What would go wrong if we did that?

**Comment by jamescheney** [comment] 2019-03-20 11:42
Argh, this was a while ago, paging back in...

So say you have (in OCaml)

```
let rec map f xs = 
  match xs with
    [] -> []
  x::xs -> (f x) :: (map f xs)
```

This is fine, we generalize over the FTVs of the body and get `(a -> b) -> [a] -> [b]` (using Haskell type syntax since backticks are bad in markup).

Now suppose we do
```
let rec map f xs = 
  match xs with
    [] -> []
  x::xs -> ((fun y -> y) (f x)) :: (map f xs)
```

ie. we ad a useless identity function.  This is fine, but we don't abstract over its type to make a polymorphic identity inside map, since (in System F terms) it's inside the scope of the `a`/`b` bindings.  But, in order for subsequent closure conversion to work, we do need to work out what (bound-later) type variables the `(fun y -> y)` depends on, at whatever stage these get made explicit.  

So I *think* the answer is that what you suggest should work, as long as we are doing it as part of the same translation from inferred/implicit type abstraction/application to explicit as the one that deals with making named-function-declarations type variables and applications explicit.

But I think I would have to sit down with a specification of the pre- and post-translation type systems (and the translation) to be sure.  Maybe others who have worked on this kind of thing more recently can be more confident.

**Comment by jamescheney** [comment] 2019-03-20 11:50
So concretely, one (possibly wasteful) approach could be to abstract function literals over all type variables currently in scope, and immediately apply them; 

`(fun x -> x) ==> /\a./\b.(fun x -> x)[a][b]`

alternatively we can just abstract over type variables that appear in the argument or result types, this should be equivalent if we are able to determine these types (i.e. if they are available as synthesized attributes at the corresponding point in the visitor traversal).

`(fun x -> x) ==> /\b.(fun x -> x)[b]` 

since this occurrence is only applied at `b` to the result of `f`.

**Comment by jstolarek** [comment] 2019-03-20 12:11
Sorry, I don't follow. If we have:

```
let rec map f xs = 
  match xs with
    [] -> []
  | x::xs -> ((fun y -> y) (f x)) :: (map f xs)
```
then by looking at `(fun y -> y)` literal I would infer it's type as `/\ c. (fun (y : c) -> y)` and then when `(f x)` is used as an argument I would apply type variable `b` so that we get `(fun (y : b) -> y) (f x)` (I've placed type annotation on the binder for clarity). I don't know whether this is possible in Links' typechecker but that is what I would do on paper. 

> we don't abstract over its type to make a polymorphic identity inside map, since (in System F terms) it's inside the scope of the a/b bindings. 

So I just did that in my example above. Why wouldn't that work? Why is being in scope of a and b bindings a problem?

**Comment by jamescheney** [comment] 2019-03-20 13:52
I'm not saying it's a problem, just that in ML-like languages function literals are not type-abstracted as far as I know, only top-level definitions or let-bound expressions.   So what you have in mind seems fine, but there may be a more subtle issue that I'm not aware of.

**Comment by dhil** [comment] 2019-03-20 14:50
I think the dictum in Hindley-Milner type systems is to only generalise at let bindings (hence the terminology "let-polymorphism"). Note in Links `fun f(...) { ... }` can be thought of as a recursive let binding.

There is an argument to made against "too much polymorphism", because polymorphism has some computational content associated with it. It matters not in Links as type erasure is part of our (current) dynamic semantics. But it matters if you care about the quality of generated code, e.g. avoid boxing everything.

**Comment by frank-emrich** [comment] 2019-03-20 19:21
I made some progress in understanding this bug, using the example Links program `fun (x) {x}`.

The relevant stages are the following, in the order they are performed.

**Type-Checking**

During type-checking polymorphic `FunLit`s /lambdas, a type abstraction is put around them:

`fun Y -> Y (x : Y) {x}`
becomes 
`TAbs Y. fun Y -> Y (x:Y) {x}`
 in `typeSugar.ml` , of overall type `forall Y. Y -> Y`. I'm using same made-up syntax here, putting function types right after the `fun`, putting types of parameters behind them, and ignoring effects. The type variable `Y` is flexible before/rigid afterwards.

This is only the case if the setting `quantified_instantiation` is true, but that's the default. If the setting is false, the function keeps using flexible type variables, meaning that it is treated monomorphically, which yields a type-correct program.

**Desguaring FunLits**

As @jamescheney mentioned, `FunLit`s are desugared into blocks in `desugarFuns.ml` (which happens after type-checking). Keeping the type abstraction from before, this looks as follows:

Our previous
```
TAbs Y. fun Y-> Y (x:Y) {x}
```
translates to the following (i.e., `TAbs Y` followed by a block containing a normal, named function binding)
```
TAbs Y. { 
  fun Y-> Y freshfun(x:Y) {x}
  freshfun
} 
```

However, at this point, `desugarFuns.ml` doesn't apply the usual HM generalization rule to the newly created function binding. Note that `freshfun` is monomorphic. This is essentially what @jstolarek observed by the `tyvars` not being filled. 

**IR Translation**

Subsequently, sugartoir turns this into IR code similar to the following:

```
fun Y-> Y freshfun(x:Y) {x}
TAbs Y. freshfun
```
which exhibits the problem at hand: in `freshfun`, the rigid type variable `Y` is not bound.
In general, `sugartoir.ml` seems to require that the generalization rule is applied to all bindings.

**Conclusion**

If `quantified_instantiation` is set, we type lambdas polymorphically, which, as James and Daniel stated, is not what a standard HM system does.

This would be fine, if our transformation from `FunLit`/lambda to `Fun`/let-bound function would perform the usual generalization step, which `sugartoir.ml` seems to rely on. In our case, `desugarFuns.ml` would have to generalize the function and insert a type application. This would result in the following program after the `desugarFuns.ml` stage


```
TAbs Y. { 
  fun forall Z. Z-> Z freshfun(x:Z) {x}
  TApp freshfun [Y]
} 
```
which `sugartoir.ml` would then translate to something type-safe. Alternatively, we could move the translation step for `FunLit` that currently happens in `desugarFuns.ml` and perform it has part of `typeSugar.ml`, without introducing the `TAbs`.

**Comment by jstolarek** [comment] 2019-03-25 11:32
@frank-emrich, there's something I don't understand in your last code snippet. Isn't it the case that in order for `TApp freshfun [Y]` to be a well-formed expression, `freshfun` would need to have a `TAbs`? Or perhaps inserting `tyvars` into a `Fun` expression fulfils that role?

**Comment by frank-emrich** [comment] 2019-03-25 14:51
> Or perhaps inserting `tyvars` into a Fun expression fulfils that role?

Yes, exactly. Our `Fun` and `Let` binding forms have a builtin type abstraction, which is the `tyvars` list you mentioned.

**Comment by jstolarek** [comment] 2019-03-26 13:59
@frank-emrich, here's a smaller example of type mismatch error: `fun (f) {fun (x){f (x)}}`

**Comment by jstolarek** [comment] 2019-07-29 12:15
I'm closing this ticket in favour of specific tickets dedicated to differnt IR typing errors. And so:

1. `fun (x) {x};` and `fun (x) {1};` - see #693

2. `for (x <- []) []` IR-typechecks correctly.

3. `fun () {query {[]}}` no longer causes "incompatible effects" but causes "unbound type variable" and type mismatch errors - see #694 and #620

4. `fun (f,g) {fun (x){f (g(x))}}` now causes multiple "unbound type variable" errors and type mismatch error. See #693 and #620.

5. `fun (x) {<a>{x}</a>}` now produces "unbound type variable" and type mismatch error. See #693 and #620.

It seems that a large number of originally reported errors have gone away (for whatever reasons) and we are primarily dealing with #693/#694 and #620.

**Closed by jstolarek** 2019-07-29 12:15 UTC
Labels: IR Typing, bug
