### ISSUE TITLE
"Type mismatch" IR typechecking error with Prelude `fork`

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#874] opened 2020-07-01 11:22 UTC
Compiling the following function from Prelude:
```
#sig fork : forall s::Session,e::Row.((s) ~e~> ()) ~e~> ~s
sig fork : forall s::Session,e::Row.((s) {SessionFail:[||]}~> ()) ~e~> ~s
fun fork(f) {
  var ap = new ();
  var _ = spawnAngel {
    f(accept(ap))
  };
  request(ap)
}
```
produces an IR typechecking error:
```
***: IR Type Error: Type mismatch:
 Expected:
  () {|SessionFail:() {}-> [||]}~@ ()
 Actual:
  () {SessionFail:() {}-> [||]}~@ ()
occurring in IR binding:
(Ir.Fun
   ((1809,
     (() {|SessionFail:() {}-> [||]}~@ (), "_fun__g114", Var.Scope.Local)),
    ([], [],
     ([(Ir.Let ((1808, (454::Session, "", Var.Scope.Local)),
          ([],
           (Ir.Apply (
              (Ir.TApp ((Ir.Variable 52),
                 [454::Session; { |SessionFail:() {}-> [||] }])),
              [(Ir.Variable 1806)])))
          ))
        ],
      (Ir.Apply ((Ir.Variable 1805), [(Ir.Variable 1808)])))),
    None, CommonTypes.Location.Unknown, false))
```
Reproduced on c3bf313d with following config:
```
typecheck_ir=true
fail_on_ir_type_error=true
prelude=tests/empty_prelude.links
optimise=false
debug=true
print_types_pretty=true
recheck_frontend_transformations=true
hide_fresh_type_vars=false
show_flavours=true
show_quantifiers=true
show_raw_type_vars=true
```
Set `print_types_pretty=false` to see the full structure of types in the error message.

**Comment by jamescheney** [comment] 2020-07-01 18:58
Ah, I think this is actually a duplicate of #876: the type equality comparison is failing because type equality is not reflexive on any type involving Lolli.  (This applies both to my minimized example and the original fork function: the spawnAngel block gets expanded out to a function that is supposed to be linear, even though the declared type is nonlinear.)

**Closed** 2020-07-02 11:37 UTC
Labels: IR Typing
