### ISSUE TITLE
rename built "links" executable?

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#152] opened 2017-03-13 11:11 UTC
We currently build the "links" executable and rename it to "linx" during OPAM package installation only.  I suggest we change the executable name built by the makefile to "linx" for uniformity.

**Comment by jstolarek** [comment] 2017-03-17 10:30
I guess this is a duplicate of #72 :-) I'm in favour of renaming the executable but I'm not sure if other's agree. @slindley ?

**Comment by jamescheney** [comment] 2017-03-28 14:43
#72 was closed as a result of adding a line that renames "links" to "linx" when it is installed by OPAM.  This means that you have to do something different if you are using the OPAM package vs. if you are building from source.  My proposal is that we should change the name of the executable to "linx" when it is built rather than building it as "links" and then renaming.  I thought this is what was intended by "renaming" in #72.

**Comment by jstolarek** [comment] 2017-03-28 14:58
> My proposal is that we should change the name of the executable to "linx" when it is built rather than building it as "links" and then renaming.

That was my original proposal as well.

**Comment by jamescheney** [comment] 2017-03-30 13:38
We discussed this and the outcome was to keep the Makefile as is but add a symlink "linx" -> "links" in whatever location "links" is built.  (Perhaps also do this as part of make install.)  I will do this.

**Closed** 2017-05-08 11:52 UTC
Labels: cleanup
