### ISSUE TITLE
Generalisation breaks the value restriction

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#871] opened 2020-07-01 09:32 UTC
The program:

```
var foo = spawn { () }; ()
```
compiled with following configuration on commit 2f71a065:
```
prelude=tests/empty_prelude.links
optimise=false
recheck_frontend_transformations=true
print_types_pretty=false
hide_fresh_type_vars=false
show_flavours=true
```
produces a type error:
```
error: transformation pass 'funs' produced an ill-typed program.

Type error: Because of the value restriction there can be no
free rigid type variables at an ungeneralisable binding site,
but the type `(Types.Meta
   Point @ 0x7f1fd9f22978 (Types.Application
                             ({ Types.Abstype.id = "Process";
                                name = "Process";
                                arity =
                                [(CommonTypes.PrimaryKind.Row,
                                  (CommonTypes.Linearity.Any,
                                   CommonTypes.Restriction.Effect))
                                  ]
                                },
                              [(CommonTypes.PrimaryKind.Row,
                                (Types.Row
                                   ({},
                                    Point @ 0x7f1fd95c0d60 (Types.Var
                                                              (394,
                                                               (CommonTypes.PrimaryKind.Row,
                                                                (CommonTypes.Linearity.Unl,
                                                                 CommonTypes.Restriction.Any)),
                                                               `Rigid)),
                                    false)))
                                ])))' has free rigid type variables.
In expression: var foo = spawn { () }.
```

Below I'm copying @slindley explanation from [here](https://github.com/links-lang/links/issues/865#issuecomment-650811461):

The error in function desugaring arises because of the generalisation that occurs inside function literals. This seems harmless enough, and indeed it would be if the implementation of generalisation was a bit more careful. Here's roughly what's going on. The following
```
var (z : { |%e}) = spawnAt { |%e} (fun () {...});
```
is intended to be desugared into code that explicitly names, and generalises, the anonymous function:
```
var (z : { |%e}) = spawnAt [{ |%e}] (fun f[e'::Row]() {...}; f[{ |%e}])
```
but instead it comes out more like this
```
var (z : { |e}) = spawnAt [{ |e}] (fun f[e::Row]() {...}; f[{ |e}])
```
(using suitable notation for type abstraction and type application).

The row variable `%e` doesn't appear in the type environment so it gets generalised in the type of the anonymous function. But this operation incorrectly mutates the `%e`s appearing in the type of `z` and applied as a type parameter to `spawnAt` turning them into rigid variables.

One solution is to do a more careful implementation of generalisation that renames variables by traversing the term rather than using mutation. This may be worthwhile implementing anyway. (I'm sure I talked to Jonathan about doing this at some point.)

Another solution is to disable the generalisation. This is sound, but breaks some of the test cases as well as the IR checker (which is probably making some dubious assumptions anyway).

**Comment by jamescheney** [comment] 2020-07-02 15:49
Assigning to @slindley for reconsideration in August.

**Comment by jamescheney** [comment] 2020-09-16 16:56
This is milestoned 0.9.2, which we hoped to get released around now.  Is it likely to be resolved in the next week or so, or should we postpone it?

(0.9.2 is needed as a bugfix release due to #807 )

**Comment by frank-emrich** [comment] 2021-06-11 21:29
When reproducing this, I noticed that the original error message ("Type error: Because of the value restriction there can be no
free rigid type variables... ") doesn't seem to occur for this example anymore. Could you verify this, @jstolarek?

However, the underlying issue as analyzed by Sam still exists: Generalizing the lambda when turning it into a named function does indeed mutate occurrences of the same variable outside of the generalized function body.

**Comment by frank-emrich** [comment] 2021-06-11 22:31
Side note: This is what causes the `makeEndBang` prelude function fail IR type-checking.

**Closed** 2021-06-17 16:55 UTC
Labels: IR Typing, bug
