### ISSUE TITLE
Session-typed chatserver is broken

### ISSUE THREAD

**Issue by SimonJF** [links-lang/links#1027] opened 2021-07-21 13:01 UTC
Running the session-typed chatserver (`examples/sessions/chatserver.links`) and entering a name gives the following error:

```
jslib.js:342 Uncaught Error: Assertion failed: LINKS.singleXmlToDomNodes expected a XmlItem, but got [object Object]
    at Object.assert (jslib.js:342)
    at Object.LINKS.singleXmlToDomNodes (jslib.js:1369)
    at jslib.js:1101
    at Object.forEach (jslib.js:29)
    at Object.XmlToDomNodes (jslib.js:1100)
    at _domReplaceChildren (jslib.js:2005)
    at (index):3572
    at _applyCont_HO (jslib.js:3574)
    at (index):3571
    at _applyCont_HO (jslib.js:3574)
```

**Comment by dhil** [comment] 2021-07-21 17:27
How do you run the example?
```
./links --set=types_pretty_printer_engine=old --config=handlers.config --path=examples/sessions/chatserver examples/sessions/chatserver/chatServer.links
Raised at Links_core__Sugartoir.Eval.eval in file "core/sugartoir.ml", line 1123, characters 14-26
Called from Links_core__Sugartoir.Interpretation.letrec.(fun).body in file "core/sugartoir.ml", line 705, characters 24-31
Called from Links_core__Sugartoir.Interpretation.S.rec_binding.(fun) in file "core/sugartoir.ml", line 335, characters 42-49
Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23
Called from Links_core__Sugartoir.Interpretation.S.rec_binding in file "core/sugartoir.ml", line 331, characters 13-384
Called from Links_core__Sugartoir.Interpretation.letrec in file "core/sugartoir.ml", line 719, characters 13-31
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.BindingListMonad.bind in file "core/sugartoir.ml", line 210, characters 20-23
Called from Links_core__Sugartoir.Eval.compile in file "core/sugartoir.ml", line 1301, characters 12-56
Called from Links_core__Sugartoir.program in file "core/sugartoir.ml", line 1339, characters 20-41
Called from Driver.Phases.Compile.IR.run in file "bin/driver.ml" (inlined), line 64, characters 8-50
Called from Driver.Phases.whole_program in file "bin/driver.ml", line 170, characters 6-165
Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 31, characters 17-27
Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 36, characters 4-11
***: Error: "Assert_failure core/sugartoir.ml:1123:14" 
```

**Comment by SimonJF** [comment] 2021-07-22 08:42
Have you got `session_exceptions=true` in your config?

(In either case, we shouldn't be getting an assert failure there...)

**Comment by dhil** [comment] 2021-07-22 14:26
I was missing that option!

However, I think my hunch is right. The problem is that unresolved server value are passed around. If I type in the string `asd` I get the following object which has not been through `resolveServerValue`
```
_tag: "String"
_value: "asd"
__proto__: Object
```

**Comment by SimonJF** [comment] 2021-07-22 14:40
Yes -- the only way that `SESSION_MESSAGE_DELIVERY` will have been fired is if a message has been routed via the server (i.e., has been sent via a process located on the server, or has been sent by a process on another client, and then routed by the server).

**Comment by dhil** [comment] 2021-07-22 14:42
Ok. I will try. I reckon this code has been broken all along, but just hasn't been discovered until now. I suppose you have never tried to send a function over a channel.

**Comment by SimonJF** [comment] 2021-07-22 14:49
I think it's probably just a continuation of bugs masking other bugs...

**Comment by dhil** [comment] 2021-07-22 14:51
I got the example working again.

**Comment by dhil** [comment] 2021-07-22 14:52
I still think the whole thing is a little fragile. As I have mentioned elsewhere, we need a structured approach to receiving/resolving server value, and quite possibly also for client to server, or client to client.

**Comment by SimonJF** [comment] 2021-07-22 14:53
Yes. Before, there wasn't a big distinction between the JS internal representation and the "wire format". Actually separating these out is a big step.

**Comment by dhil** [comment] 2021-07-22 14:59
Agree. Nevertheless, it now shows how sloppy we have been w.r.t. to handling of server side values (not to mention the previous scheme was broken c.f. #353).

**Closed** 2021-07-22 15:10 UTC
