### ISSUE TITLE
Links interactive shell outputting to stderr when it should be stdout

### ISSUE THREAD

**Issue by NickWu007** [links-lang/links#293] opened 2017-10-26 22:37 UTC
Hi,

I was playing with Links and trying to make an online interactive shell for Links, and I realised when I input something like:

`var a = 2;`

I would get `a = 2 : Int` which is expected, but it is in `stderr` instead of `stdout`.

This is a bit strange to me since this message is not an error, more like a helpful reminder, which technically should be through `stdout`. If I type in some gibberish then the message would make sense to be in `stderr`.

Let me know if this makes sense.
Nick

**Comment by NickWu007** [comment] 2017-10-27 09:44
This would be a better illustration. Red background means it is coming from `stderr` and light grey is `stdout`.

<img width="781" alt="screen shot 2017-10-27 at 10 42 21" src="https://user-images.githubusercontent.com/17936144/32098180-c9cdfd86-bb03-11e7-89d0-f5a036b24b7f.png">

**Comment by dhil** [comment] 2017-10-27 10:07
I am not sure what the rationale (if any) is behind this decision. But the behaviour is caused by `prerr_endline` on line 294 in `links.ml` (c.f. https://github.com/links-lang/links/blob/master/links.ml#L294). 

If you want to change this now, I suggest you fork the repository and patch it yourself. Looking at the source, maybe line 267 will have to be changed as well (c.f. https://github.com/links-lang/links/blob/master/links.ml#L267)

**Comment by NickWu007** [comment] 2017-10-27 10:16
Hi Daniel,

Thanks for the explanation. I think it would make sense to change the lines you mentioned in the master branch as well.

Nick

**Comment by jamescheney** [comment] 2017-12-10 11:31
should be fixed by #303

**Closed by jamescheney** 2017-12-10 11:31 UTC
Labels: question
