### ISSUE TITLE
Top-level variables' types may contain flexible type variables

### ISSUE THREAD

**Issue by SquidDev** [links-lang/links#651] opened 2019-06-18 17:25 UTC
```
fun curriedFun()(x) { }
var varFun = curriedFun();
```

Given the above program, Links infers the types `(Int) -%a-> ()` for `varFun`. However, the type is not quantified, and so the effect variable is unified with the first usage of `varFun`.

Consequently, attempting to do the following will fail to compile, as it first unifies `%a` with `{Yield | a}`, and then fails to unify it with `{Yield | b}`.

```
sig foo : () {Yield | a} -> ()
fun foo() { varFun(0) }

sig bar : () {Yield | b} -> ()
fun bar() { varFun(0) }
```

This cropped up as part of trying to work out why [the handlers test file](https://github.com/links-lang/links/blob/master/examples/handlers/tests.links#L34) fails to type check during desugaring - it uses a similar pattern, which type checks fine, but fails after `DesugarFuns`.

**Comment by jamescheney** [comment] 2019-06-18 17:46
Huh.  A couple of things are strange:

- when I do the first two lines, I get 
```
links> fun curriedFun()(x) {};
curriedFun = fun : () -> (_) -> ()
links> var varFun = curriedFun();
varFun = fun : (_) -> ()
```
so the type of `varFun` certainly has `(Int) -%a-> ()` as an instance, but shouldn't be instantiate to `Int` this early.

Then if I do:
```
links> sig foo : () {Yield | a} -> ()
...... fun foo() { varFun(0) };
foo = fun : () {Yield:() {}-> ()|_}-> ()
links> varFun;
fun : (Int) {Yield:() {}-> ()|_}-> ()
```
now the first `_` in varFun is instantiated to `Int`.  This shows that this is happening even for ordinary unquantified variables, not just effect vars.  So for example calling `varFun` twice in the same function with different argument types should also work, but won't:
```
links> var varFun = curriedFun();
varFun = fun : (_) -> ()
links> (varFun(0),varFun("asdf"));
<stdin>:1: Type error: The function
    `varFun'
has type
    `(Int) {}~> ()'
while the arguments passed to it have types
    `String'
and the currently allowed effects are
    `wild'
In expression: varFun("asdf").
```

I think `generalise.ml` or things that call it (in typeSugar?) are likely culprits... somewhere, the free (flexible) variables of inferred types should be being quantified and turned into rigid vars before we proceed with typechecking the next declaration.

**Comment by slindley** [comment] 2019-06-18 18:00
This is exactly the expected behaviour. There is a flexible variable there because of the value restriction. The pretty-printer doesn't distinguish between flexible and rigid type variables by default - which is perhaps what is confusing you.

**Comment by jamescheney** [comment] 2019-06-18 18:37
Ah, right, forgot about that.  In OCaml you get this instead:

```
# let curriedFun() (x) = ();;
val curriedFun : unit -> 'a -> unit = <fun>
# let varFun = curriedFun();;
val varFun : '_weak1 -> unit = <fun>
```
which gives you a hint that the free type variable wasn't generalized.

Think this can be closed...

**Comment by jamescheney** [comment] 2019-06-18 18:37
(unless we want to morph it into a feature request for pretty-printing the "weak" type variables differently...)

**Comment by dhil** [comment] 2019-06-18 19:33
I think we should definitely adapt the pretty printer for types to print "weak" type variables.

I was under the impression, that we had decided not generate types with flexible type variables. I was wrong. I had not thought about what consequences it would have programming in the REPL.

**Comment by slindley** [comment] 2019-06-18 22:10
If you enable `show_flavours` then you will see the explicit distinction

    links> fun (x) {x};
    fun : (a::Any) -> a::Any
    links> fun (x) {(x, x)};
    fun : (a) -> (a, a)
    links> fun f(x) {(x, x)};
    f = fun : (a) -> (a, a)
    links> fun g(x) {x};
    g = fun : (a::Any) -> a::Any
    links> var x = id(id);
    x = fun : (a::Any) -> a::Any
    links> @set show_flavours true;
    links> fun (x) {x};
    fun : (%a::Any) -%-> %a::Any
    links> fun (x) {(x, x)};
    fun : (%a) -%-> (%a, %a)
    links> fun f(x) {(x, x)};
    f = fun : (a) -> (a, a)
    links> fun g(x) {x};
    g = fun : (a::Any) -> a::Any
    links> var x = id(id);
    x = fun : (%a::Any) -%-> %a::Any

Initially we thought it might be confusing to show flavours (flexible vs rigid) by default, but arguably it would be better to be explicit.

Different systems adopt different conventions. SML/NJ and other SMLs typically generate fresh rigid type variables instead of flexible type variables. These aren't particularly useful. Currently we follow OCaml by generating flexible variables whenever the value restriction prevents generalisation. OCaml differs in relying on context to distinguish between rigid and flexible type variables (in type ascriptions type variables are flexible by default; in module definitions they're rigid).

I did have a discussion with @dhil a quite recently where I suggested that it would be nice if we could get rid of flexible type variables in the backend (we probably don't want to perform unification during backend type-checking). OTOH they're quite handy for the REPL.

Of course, if they ever get in the way then you can always eta-expand your code to allow generalisation to take place.

**Comment by dhil** [comment] 2019-06-19 20:20
> Initially we thought it might be confusing to show flavours (flexible vs rigid) by default, but arguably it would be better to be explicit.

I agree, we should turn on `show_flavours` by default.

**Comment by dhil** [comment] 2019-06-20 14:28
Of course there is no free lunch.

There seems to be a bug in the type renderer when `show_flavours` is enabled.
```
links> map;
fun : ((a) -b-> c, [a]) -b-> [c]
links> @set show_flavours true;
links> map;
fun : ((%a) -%b-> %c, [%a]) -%b-> [%c]
```
The type of map is rendered as being "weakly" polymorphic. It seems nonsensical to me.
```
links> map(id, [1,2,3]);
[1, 2, 3] : [Int]
links> map(id, ["foo","bar"]);
["foo", "bar"] : [String]
```
It seems to be the case for all globals.

**Comment by dhil** [comment] 2019-06-20 14:41
OK. I understand now that it is correct, because an applied occurrence of `map` triggers an instantiation.

**Comment by jamescheney** [comment] 2019-07-16 10:46
This seems closable, or we should rename the issue to " turn on `show_flavours` by default."  (or someone just does it).

**Comment by dhil** [comment] 2019-07-16 16:02
I have changed my mind on the `show_flavours` by default. It is actually highly confusing due to the way instantiation works. Nevertheless, I think we can close this now.

**Closed by dhil** 2019-07-16 16:02 UTC
Labels: confusion
