### ISSUE TITLE
Hardcoded paths to JavaScript files

### ISSUE THREAD

**Issue by vcgalpin** [links-lang/links#931] opened 2020-11-03 11:11 UTC
The paths to `vdom.js` and `virtual-dom.js` appear to be hardcoded in a way which is incompatible with the location of the JavaScript files in the opam install. The opam install uses the following config options
```
jsliburl=/lib/js
jslibdir=/Users/vashti/.opam/default/lib/links/js
```
but if the two js files above (which are missing in the opam install --see issue #930) are copied into the jslibdir then they are not found when running links.

A solution was to create a local lib directory containing those two files plus jslib.js and changing the config to
```
jsliburl=/lib
jslibdir=lib 
```
but moves the js files out of the opam lib structure.

(BTW, this problem was hard to debug because links tries to do something reasonable with some other files and one gets a half functional webpage.)

**Comment by dhil** [comment] 2020-11-03 17:47
It is probably a mistake that `vdom.js` and `virtual-dom.js` aren't included in the OPAM package given that examples of their use are included. However, the behaviour you observe regarding locating the files is currently the intended behaviour --- however strange it may sound. The reason for this behaviour is the current design of the `alien` interface and the way source files for `alien` declarations are resolved. I have previously written about some of the problems with the current design in #786.

**Comment by dhil** [comment] 2020-11-03 19:36
I have opened PR #934 which contains fix for this particular issue. It is really only treats the symptoms, rather than the underlying problem, as a solution to the general problem with resolution of alien source files requires some careful design considerations.

**Closed** 2020-11-10 20:40 UTC
Labels: bug
