### ISSUE TITLE
Unsound hoisting out of type abstractions

### ISSUE THREAD

**Issue by dhil** [links-lang/links#339] opened 2018-06-11 20:08 UTC
There is a critical bug in the transformation pass from AST to IR (i.e. `sugartoir.ml`) as it hoists computations from within type abstractions. This is problematic because it causes reduction under binders to happen and obstructs tail calls. Below is a minimal example which suffers from the aforementioned problems
```
sig f : () {}~> a
fun f() {
  switch(A) {
    case A -> f()
  }
}
f
```

The type checker produces the following decorated AST
```
([(`Funs ([(("f", (Some () {}~> _), ...), `Unl,
            (([(954, (`Unl, `Any), `Type (...))], (Some (() {}~> _, [None]))),
             ([[]],
              (`Block (([],
                        (`Switch (((`ConstructorLit (("A", None, (Some [|A|]))),
                                    ...),
                                   [((`Variant (("A", None)), ...),
                                     (`Block (([],
                                               (`TAbstr ((ref ([(965,
                                                                 (`Unl, `Any),
                                                                 `Type (
                                                                 ...))]),
                                                          (`FnAppl ((
                                                                    (
                                                                    `TAppl (
                                                                    (
                                                                    (
                                                                    `TAbstr (
                                                                    (
                                                                    ref (
                                                                    [(964,
                                                                    (`Unl,
                                                                    `Any),
                                                                    `Type (
                                                                    ...))]),
                                                                    (
                                                                    `TAppl (
                                                                    (
                                                                    (
                                                                    `Var (
                                                                    "f"), ...),
                                                                    [`Type (
                                                                    `MetaTypeVar (
                                                                    ...))])),
                                                                    ...))),
                                                                    ...),
                                                                    [`Type (
                                                                    `MetaTypeVar (
                                                                    ...))])),
                                                                    ...), 
                                                                    [])),
                                                           ...))),
                                                ...))),
                                      ...))
                                     ],
                                   (Some _))),
                         ...))),
               ...))),
            `Unknown,
            (Some (`Function (([], ([("wild", `Present (`Unit))], `Closed),
                               `TypeVar (("a", None, `Rigid)))),
                   (Some () {}~> _))),
            ...)]),
   ...)],
 (Some (`TAbstr ((ref ([(969, (`Unl, `Any), `Type (...))]),
                  (`TAppl (((`Var ("f"), ...), [`Type (`MetaTypeVar (...))])),
                   ...))),
        ...)))
```
Note the function application inside the type abstraction ``(`TAbstr ((ref ([(965, (`Unl, `Any), `Type (...))]), (`FnAppl (( ...``.

The transformation into IR hoists this function application
```
([`Rec ([((391, (() {}~> _, "f", `Global)),
          ([(954, (`Unl, `Any), `Type (...))], [],
           ([`Let (((392, ([|A|], "", `Local)),
                    ([],
                     `Return (`Inject (("A", `Extend (({}, None)), [|A|]))))))
              ],
            `Case ((`Variable (392),
                    {A => ((393, ((), "", `Local)),
                           ([`Let (((394, (_, "", `Local)),
                                    ([],
                                     `Apply ((`TApp ((`TAbs (([(964,
                                                                (`Unl, `Any),
                                                                `Type (
                                                                ...))],
                                                              `TApp (
                                                              (`Variable (
                                                               391),
                                                               [`Type (
                                                                 `MetaTypeVar (
                                                                 ...))])))),
                                                      [`Type (`MetaTypeVar (
                                                              ...))
                                                        ])),
                                              [])))))
                              ],
                            `Return (`TAbs (([(965, (`Unl, `Any), `Type (...))
                                               ],
                                             `Variable (394))))));
                     },
                    None)))),
          None, `Unknown)])
   ],
 `Return (`TAbs (([(969, (`Unl, `Any), `Type (...))],
                  `TApp ((`Variable (391), [`Type (`MetaTypeVar (...))]))))))
```

Note that in the binding list, the body of the binding `Let (((394, ...` contains the application of variable `391`. The tail computation is the type abstraction ``Return (`TAbs ...`` over the variable `394`, i.e. the result of the application of `391`. Thus, the code effectively reduces under the type abstraction which is not sound in general. Furthermore, this unsound hoisting obstructs tail-call elimination as the function `f` is no longer applied in tail position.

In the current IR type abstraction and type application are values, i.e.
```
type value =
  | `TAbs of tyvar list * value       (* type abstraction: /\xs.v *)
  | `TApp of value * tyarg list       (* type application: v @ ts *)
  | ...
```
The application of `f` gets hoisted because the body of the type abstraction must be a value.

I suppose the solution is to introduce another pair of type abstraction and type application at the level of computations, i.e.
```
and tail_computation =
  | `TAbsComp of tyvar list * computation  (* /\ts. M *)
  | `TAppComp of computation * tyarg list  (* M @ ts *)
  | ...
```
such that we obtain the following tail call preserving erasure semantics
```
erase(/\ts.M) = erase(M)
erase(M @ ts) = erase(M)
```
In order to obtain call-by-value semantics, we need to permit evaluation of type abstraction to a polymorphic value, i.e.
```
         M --> return v          M pure
-------------------------------------------------
  let x = /\ts.M in N --> N[/\ts.return v/x]
```

**Comment by slindley** [comment] 2018-06-11 22:51
The cause was an application of a type isomorphism in type inference that violates the value restriction. Fixed by disabling use of the type isomorphism by default (f41bf77e6).

**Closed by slindley** 2018-06-11 22:51 UTC
Labels: bug
