### ISSUE TITLE
Use of dedup and distinct

### ISSUE THREAD

**Issue by vcgalpin** [links-lang/links#1067] opened 2021-11-15 12:26 UTC
I'm not getting the results I expect from the following code. The `numbers` table has one integer field; there are 1000 rows, each containing a value 0 between 99. I'm running version 0.9.4 installed via opam on MacOS 11.6.1 and the database and table are defined as follows:
```
var db = database "links";
var numbers = table "numbers" with (number: Int) from db;
```
This is the output from the REPL (with timing information removed for clarity). I've explicitly used `query mixing` but I also have `mixing_norm=on` in the config file.
`dedup` outside the query gives the expected result.
```
links> length ( dedup (query mixing { for (x <-- numbers) [x] }));
Running query: 
select (t2386."number") as "number"
from "numbers" as t2386
Finishing process MAIN
100 : Int
```
`dedup` inside the query gives an error.
```
links> length (query mixing { dedup(for (x <-- numbers) [x] )});
***: Internal Error in lib.ml (Please report as a bug): Unoptimized table access!!!
```
and `distinct` appears to do nothing as it returns the same list as when it isn't used.
```
links> length (query mixing { for (x <- distinct(numbers)) [x] });
Running query: 
select (t2393."number") as "number"
from "numbers" as t2393
Finishing process MAIN
1000 : Int
```

**Comment by wricciot** [comment] 2021-11-15 14:59
Thanks @vcgalpin, will have a look at this tomorrow morning.

**Comment by jamescheney** [comment] 2021-11-15 15:27
I get this also with a query using `factorials`:

```
links> dedup(query mixing {(for (x <-( asList(factorials)) ++ (asList(factorials))) [(a=x.i)])});
[(a = 1), (a = 2), (a = 3)] : [(a:Int)]
links> query mixing {dedup(for (x <-( asList(factorials)) ++ (asList(factorials))) [(a=x.i)])};
***: Internal Error in lib.ml (Please report as a bug): Unoptimized table access!!!
```
The internal error is a clumsy way of saying that the `distinct` operator (that should be being massaged into a position where  DISTINCT can be used in SQL) is instead surviving until query execution time, and we are trying to actually execute the library code for it, which is a stub that just raise the above error.  This should never happen because everything inside the query brackets should have been turned into an SQL query, so I suspect there may just be a silly logic bug / configuration issue that means that for some reason the `query mixing` code above is not being compiled to SQL at all and Links is just trying to run it directly.

**Comment by jamescheney** [comment] 2021-11-15 15:33
While trying different things I also happened across this, which seems likely to be a different problem:
```
links> query {for (x <-- factorials) [(a=x.i),(a=x.f)]};
[(a = 1), (a = 1), (a = 2), (a = 2), (a = 3), (a = 6)] : [(a:Int)]
links> query mixing {for (x <-- factorials) [(a=x.i),(a=x.f)]};
***: Fatal error : body 
links> query nested {for (x <-- factorials) [(a=x.i),(a=x.f)]};
[(a = 1), (a = 2), (a = 3), (a = 1), (a = 2), (a = 6)] : [(a:Int)]
links> query delat {for (x <-- factorials) [(a=x.i),(a=x.f)]};
***: Fatal error : body 
```
Note that in this query (which is the same in each case except for the policy) the body yields a collection with two elements per iteration, one containing the `i` field and the other the `f` field.  This should be (and is, with flat and nested policies) turned into a union of two select-from-where queries.

**Comment by wricciot** [comment] 2021-11-16 11:59
Ok, there seem to be a few problems going on here.

The "unoptimized table access" happens because the "used_database" function in QueryLang doesn't detect tables within set operations (i.e. within dedup). It's silly and I'm unsure when we had this regression, but it's a one line fix.

The "distinct does nothing" bug seems to be caused by normalization essentially "throwing away" the distinct call. This shouldn't happen and I'm still trying to understand what is going on.

The "Fatal error : body" bug arises at SQL generation time because the normal form obtained is not in the expected grammar, so I will have to investigate what goes wrong with normalization.

@vcgalpin I will let you know when everything is fixed. For now, thanks!

**Comment by wricciot** [comment] 2022-01-11 18:07
I have promoted the problem indicated by @jamescheney in his second comment to a separate issue #1075 because it is not directly related to deduplication. It will be fixed separately.

**Closed** 2022-01-12 23:44 UTC
Labels: bug
